openapi: '3.0.4'
info:
  title: Shopping list and recipes API.
  description: Shopping list and recipes API.
  version: 1.0.0
servers:
  - url: http://localhost/api/v1
tags:
  - name: recipe
    description: A recipe
  - name: ingredient
    description: An ingredient in a recipe or an item in a shopping list
paths:
  /recipes:
    get:
      tags:
        - recipe
      summary: Gets recipes
      operationId: getRecipes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": '#/components/schemas/Recipe'
  /recipes/{recipeId}/ingredients:
    get:
      tags:
        - ingredient
      summary: Gets ingredients for a recipe
      operationId: getIngredientsByRecipe
      parameters:
        - name: recipeId
          in: path
          description: ID of recipe to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": '#/components/schemas/Ingredient'
        '400':
          description: Invalid ID supplied
        '404':
          description: Recipe not found
  /shoppingitems:
    get:
      tags:
        - ingredient
      summary: Gets shopping list items
      operationId: getShoppingItems
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": '#/components/schemas/Ingredient'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    Unit:
      type: string
      enum:
        - tsp
        - tbsp
        - dsp
        - cup
        - mg
        - g
        - kg
        - ml
        - l
        - oz
        - lb
        - floz
        - pint
        - qt
        - gallon
        - dash
        - pinch
        - stick
        - slice
        - piece
        - clove
        - head
        - sprig
        - bunch
        - stalk
        - ear
        - pod
        - wedge
        - flake
        - cube
        - chunk
    NutritionUnit:
      type: string
      enum:
        - kilojoules
        - calories
        - grams
    NutritionType:
      type: string
      enum:
        - carbohydrates
        - energy
        - protein
        - fat
        - fibre
        - saturatedFat
        - saturates
        - sodium
        - sugar
        - transFat
    DurationType:
      type: string
      enum:
        - preparation
        - cooking
        - resting
        - cooling
        - marinating
        - freezing
        - defrosting
        - serving
        - soaking
        - baking
        - drying
        - fermenting
        - pickling
        - brining
        - curing
        - chilling
        - steeping
    Duration:
      type: object
      required:
        - durationType
        - time
      properties:
        durationType:
          "$ref": '#/components/schemas/DurationType'
        time:
          type: integer
          format: int32
          description: 'time in minutes'
    IngredientGroup:
      type: object
      required:
        - ingredients
      properties:
        title:
          type: string
          description: 'optional title for the ingredient group'
        ingredients:
          type: array
          items:
            "$ref": '#/components/schemas/Ingredient'
    Ingredient:
      type: object
      required:
        - product
        - unitQuantity
      properties:
        product:
          "$ref": '#/components/schemas/Product'
        quantity:
          type: integer
          format: int32
        unit:
          "$ref": '#/components/schemas/Unit'
        optional:
          type: boolean
          description: 'Indicates an optional ingredient'
        note:
          "$ref": '#/components/schemas/Note'
    Instruction:
      type: object
      properties:
        text:
          type: string
          description: 'free form text which can include text substitutions for notes and ingredients'
    Note:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
          description: 'free form text which can include text substitutions for notes and ingredients'
    NutritionInfo:
      type: object
      required:
        - type
      properties:
        valueType:
          "$ref": '#/components/schemas/NutritionType'
        valueUnit:
          "$ref": '#/components/schemas/NutritionUnit'
        value:
          type: number
          format: double
        percent:
          type: number
          format: double
    Review:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        reviewerId:
          type: string
        Rating:
          type: integer
          format: int32
          description: 'from zero to ten'
        text:
          type: string
          description: 'free form text for any reviewer comments'
    RecipeComplexity:
      type: string
      enum:
        - beginner
        - easy
        - intermediate
        - hard
        - expert
    RecipeType:
      type: string
      enum:
        - breakfast
        - brunch
        - dessert
        - drink
        - main
        - preserve
        - sauce
        - side
        - snack
        - starter
        - soup
        - pizza
    Cuisine:
      type: string
      enum:
        - french
        - italian
        - spanish
        - chinese
        - japanese
        - indian
        - thai
        - mexican
        - american
        - middleEastern
        - african
    RecipeTag:
      type: string
      enum:
        - dairyFree
        - glutenFree
        - nutFree
        - eggFree
        - freezable
        - lowFodmap
        - keto
        - paleo
        - fish
        - beef
        - lamb
        - pork
        - goat
        - vegan
        - vegetarian
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
          description: 'category of the product, e.g. fruit, vegetable, meat, poultry, dairy, etc.'
        brand:
          type: string
        unitMeasurement:
          type: number
          format: double
          description: 'unit measurement for the product, e.g. 400 (grams) for a can of tomatoes'
        measurementUnit:
          "$ref": '#/components/schemas/Unit'
        cupWeightInGrams:
          type: number
          format: double
          description: 'conversion factor for the product to cups, i.e. how many grams in one cup'
        shelfLifeInDays:
          type: integer
          format: int64
    Recipe:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: 'GUID for the recipe'
        name:
          type: string
        description:
          type: string
        imageUrls:
          type: array
          items:
            type: string
            format: uri
        creator:
          type: string
          description: 'either the individual creator or a corporate entity'
        license:
          type: string
          description: 'license details explaining how the recipe may be used'
        source:
          type: string
          description: 'name of the source of the recipe, e.g. a website or a book'
        sourceUrl:
          type: string
          format: uri
          description: 'URL of the source of the recipe'
        datePublished:
          type: string
          format: date
          description: 'date the recipe was published'
        dateModified:
          type: string
          format: date
          description: 'date the recipe was last modified'
        servings:
          type: integer
          format: int32
        duration:
          type: array
          items:
            "$ref": '#/components/schemas/Duration'
        complexity:
          "$ref": '#/components/schemas/RecipeComplexity'
          description: 'difficulty level of the recipe'
        type:
          "$ref": '#/components/schemas/RecipeType'
        cuisine:
          "$ref": '#/components/schemas/Cuisine'
        tags:
          type: array
          items:
            "$ref": '#/components/schemas/RecipeTag'        
        ingredients:
          type: array
          items:
            "$ref": '#/components/schemas/IngredientGroup'
        instructions:
          type: array
          items:
            "$ref": '#/components/schemas/Instruction'
        notes:
          type: array
          items:
            "$ref": '#/components/schemas/Note'
        nutritionInfoPerServe:
          type: array
          items:
            "$ref": '#/components/schemas/NutritionInfo'
        reviews:
          type: array
          items:
            "$ref": '#/components/schemas/Review'
